core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [

    path('dashboard', views.dashboard, name="dashboard"),

    # partnership
    path('partner-create', views.create_partnership, name="partner-create"),

    # manage institution
    path('institution-list', views.institution_list, name="institution-list"),
    path('institution-search', views.institution_search, name="institution-search"),
    path('institution-detail/<str:name>', views.institution_detail, name="institution-detail"),
    path('institution-detail/<str:name>/terminate', views.terminate_partnership, name="terminate-partnership"),

    # manage store
    path('store-create/<str:name>', views.create_store, name="store-create"),
    path("store-detail/<str:name>", views.store_detail, name="store"),

    # manage product
    path("product-create/<str:store_name>", views.create_product, name="product-create"),

    # manage user
    path("user-list", views.user_list, name="user-list"),
    path("user-create", views.create_user, name="user-create"),
]

workbench/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('account.urls', namespace="account")),
    path('office/', include('core.urls', namespace="core")),
    path('market/', include('supermarket.urls', namespace="market")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from account.models import User
import uuid

# Create your models here.


class Institution(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)     
    name = models.CharField(max_length=1000)
    address = models.CharField(max_length=3000)
    institution_manager = models.ForeignKey(User, on_delete=models.CASCADE, related_name="institution")
    date_joined = models.DateTimeField(auto_now_add=True)


class Store(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE, related_name="store")
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    capacity = models.IntegerField(default=100)
    cover_art = models.ImageField()
    verified = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)


class Product(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE, related_name="product")
    product_name = models.CharField(max_length=500)
    product_id = models.CharField(max_length=20)
    product_price = models.FloatField(default=0.00)
    product_category = models.ForeignKey("Category", on_delete=models.CASCADE, related_name="product")
    product_quantity = models.IntegerField(default=1)
    product_description = models.TextField(max_length=5000)
    sold_out = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now_add=True)


class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="image")
    file = models.ImageField()


class Category(models.Model):
    category = models.CharField(max_length=1000)


class Cart(models.Model):
    Product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="cart")
    cart_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_cart")
    empty = models.BooleanField(default=False)

core/forms.py
from django import forms
from .models import Institution, Store, Product
from account.models import User


class InstitutionCreationForm(forms.ModelForm):
    class Meta:
        model = Institution
        fields = (
            "name",
            "address",
            "institution_manager",
        )
        labels = {
            "name": "Name of Insititution"
        }


class StoreCreationForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = (
            "name",
            "owner",
            "cover_art",
            "description",
        )


class ProductCreationForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            "product_name",
            "product_price",
            "product_category",
            "product_quantity",
            "product_description",
        )


class UserCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = {
            "first_name",
            "last_name",
            "email",
        }

core/views.py
from django.shortcuts import render, redirect
from .models import Institution, Store, Cart, Category, Product
from .forms import InstitutionCreationForm, StoreCreationForm, ProductCreationForm, UserCreationForm
from django.contrib import messages
import random
import string
from account.models import User


# DASHBOARD
def dashboard(request):
    return render(request, 'core/dashboard.html')


# institution
def institution_list(request):
    institutes = Institution.objects.all()
    return render(request, "core/manage-institution/institution-list.html", {"institute": institutes})


def institution_search(request):
    if request.method == "POST":
        search = request.POST["search"]
        institute = Institution.objects.filter(name__contains=search)

        flag = 0
        if institute.exists():
            print(institute)
        else:
            flag = 1
            search = False

        return render(request, "core/manage-institution/search.html", {"search": search, "institute": institute, "flag": flag})
    else:
        return render(request, "core/manage-institution/search.html")


def institution_detail(request, name):
    institute = Institution.objects.get(name=name)

    store_list = []

    store = Store.objects.all()
    for i in store:
        if i.institution.uuid == institute.uuid:
            store_list.append(i)

    return render(request, 'core/manage-institution/institution-detail.html', {"institute": institute, "store": store_list})


# partnership
def create_partnership(request):
    form = InstitutionCreationForm()
    if request.method == "POST":
        form = InstitutionCreationForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            address = form.cleaned_data['address']
            manager = form.cleaned_data['institution_manager']

            if Institution.objects.filter(name=name).exists():
                messages.error(request, "Institution with that name already exists")
                return redirect({"core:partner-create"})

            new_institution = Institution.objects.create(name=name, address=address, institution_manager=manager)
            new_institution.save()

            messages.success(request, "Partnership Achieved Successfully")
            return redirect('core:dashboard')
        else:
            messages.info(request, "Error in field inputation")
    return render(request, "core/manage-institution/create-partnership.html", {"form": form})

def terminate_partnership(request, name):
    institute = Institution.objects.get(name=name)

    if request.GET.get("delete"):
        institute.delete()
        messages.success(request, f"Contract Terminated with {institute.name}")
        return redirect("core:dashboard")
    
    return render(request, "core/manage-institution/terminate-partnership.html", {"institute": institute})


# Stores
def stores(request):
    stores = Store.objects.all()
    return render(request, "core/manage-store/stores.html", {"stores": stores})

def store_detail(request, name):
    store = Store.objects.get(name=name)
    return render(request, "core/manage-store/store-detail.html", {"store": store})

def create_store(request, name):
    institution_name = name

    form = StoreCreationForm()
    if request.method == "POST":
        form = StoreCreationForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            owner = form.cleaned_data['owner']
            cover_art = form.cleaned_data['cover_art']

            if Store.objects.filter(name=name).exists():
                messages.success(request, "A store with this name already exists")

            elif Store.objects.filter(owner=owner).exists():
                messages.success(request, "A trader can't have more than one store")

            elif Institution.objects.filter(name=institution_name).exists():
                institute = Institution.objects.get(name=institution_name)
                    
                new_store = Store.objects.create(name=name, institution=institute, owner=owner, description=description, cover_art=cover_art, verified=True)
                new_store.save()

                messages.success(request, "Store Created and Verified Successfully")
                return redirect('core:institution', institute.name)
            else:
                messages.error(request, "No Institution of such exists")
                return redirect('core:dashboard')

        else:
            messages.info(request, "Error in field inputation")

    return render(request, "core/manage-store/create-store.html", {"form": form})


# products
def create_product(request, store_name):
    store = Store.objects.get(name=store_name)

    form = ProductCreationForm()

    if request.method == "POST":
        form = ProductCreationForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data["product_name"]
            price = form.cleaned_data["product_price"]
            category = form.cleaned_data["product_category"]
            quantity = form.cleaned_data["product_quantity"]
            description = form.cleaned_data["product_description"]

            # Creating a random id for product
            data_type = string.digits
            id_length = random.sample(data_type, 7)

            generated_id = "".join(id_length)


            new_product = Product.objects.create(store=store, product_name=name, product_id=generated_id,
                                                 product_price=price, product_category=category, 
                                                 product_quantity=quantity, product_description=description)
            new_product.save()



    return render(request, "core/manage-products/create-product.html", {"form": form, "store": store})


# manage users
def user_list(request):
    user = User.objects.all()
    return render(request, "core/manage-users/user-list.html", {"user": user})

def create_user(request):
    form = UserCreationForm
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            email = form.cleaned_data["email"]
            username = f"{first_name}.{last_name}"
            password = "1111"
   
            new_user = User.objects.create_user(first_name=first_name, last_name=last_name, 
                                                username=username, email=email, password=password)
            new_user.save()
            messages.info(request, "New user created successfully")
            
    return render(request, "core/manage-users/user-create.html")

def edit_user(request, pk):
    user = User.objects.get(id=pk)
    form = UserCreationForm(instance=user)

    if request.method == "POST":
        form = UserCreationForm(request.POST, instance=user )
        
        if form.is_valid():
            form.save()
            messages.success(request, "New user added successfully")
            return redirect("core:user-list")
        else:
            messages.error(request, "Error in form inputation")
    return render(request, "core/manage-users/user-edit.html")

def delete_user(request, pk):
    user = User.objects.get(id=pk)
    if request.GET.get("confirm"):
        user.delete()
        messages.success(request, "User deleted successfully")
    return render(request, "core/manage-users/user-delete.html")

core/templates/core/manage-institution/create-partnership.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block content %}

    <h1>Create Partnership with Institution</h1>
    <hr>

    <p><a href="{% url 'core:dashboard' %}"><span>&#x27f5</span> back</a></p>

    <form method="post">
        {% csrf_token %}

        {{ form | crispy }}
        <br>
        <input type="submit", value="Create Partnership" class="btn btn-success">
    </form>


{% endblock content %}

core/templates/core/manage-institution/institution-detail.html
{% extends 'base.html' %}


{% block content %}



<style type="text/css">
  .admin-btns{
    display: flex;
    justify-content: space-between;
  }
</style>


<p><a href="{% url 'core:dashboard' %}"><span>&#x27f5</span> back</a></p>


<h1>{{ institute.name }}</h1>
<hr width="350px">


<div class="list-of-stores">
    <h2>Stores</h2>

    <div class="messages">
      {% for message in messages %}
          <div class="alert alert-success" role="alert">
              {{ message }}
          </div>
      {% endfor %}
    </div>>

    <br>

    <div class="admin-btns">

      <a href="{% url 'core:store-create' institute.name %}">
        <button class="btn btn-primary">Open a new store</button>
      </a>
      
      <a href="{% url 'core:terminate-partnership' institute.name %}">
        <button class="btn btn-danger">Terminate Partnership</button>
      </a>
      
    </div>

    <br><br>

  {% for store in store %}
  <a href="{% url 'core:store' store.name %}">
    <Ol class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">{{ store.name }}</div>
            {{ store.description }}
          </div>
          <span class="badge bg-primary rounded-pill">{{ store.product.count }}</span>
        </li>
    </Ol>
  </a>
  {% endfor %} 
</div>


{% endblock content %}

core/templates/core/manage-institution/institution-list.html
{% extends 'core/dashboard.html' %}



{% block manage %}

    <h1>This is the list of institutions</h1>

    <form method="post", action="{% url 'core:institution-search' %}">
        {% csrf_token %}
        <input type="text", class="form-control", placeholder="Search Institutions", name="search">
    </form>

    {% block institution %}

        {% for institute in institute %}
            {{ institute.name }}
        {% endfor %}

    {% endblock institution %}

{% endblock manage %}

core/templates/core/manage-institution/search.html
{% extends 'core/manage-institution/institution-list.html' %}


{% block institution %}

    {% if search %}
        Here are the top searches that contains "{{ search }}" 
 
        {% for institute in institute %}
             <p>{{ institute.name }}</p> 
        {% endfor %}

    {% elif flag > 0 %}
        Such search doesn't exists
    {% else %}
        oops you did not search for anything
    {% endif %}

{% endblock institution %}

core/templates/core/manage-institution/terminate-partnership.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block content %}
    

<h1>Are you sure you want to terminate the contract with {{ institute.name }} institution</h1>

<form method="get">
    <input type="submit", value="delete", name="delete", class="btn btn-danger">
</form>
{% endblock content %}